### ISSUE TITLE
RSS feed missing

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io.src#18]

**Comment by deejoe** [comment]
Following through from IRC, I'll try to get this sorted as per:

http://docs.getpelican.com/en/stable/settings.html?highlight=rss#feed-settings

and tested as per

https://validator.w3.org/feed/check.cgi?url=Http%3A%2F%2Fwww.interlockroc.org

**Comment by aks4896** [comment]
Added atom feed.
