### ISSUE TITLE
Base url does not redirect to www

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io.src#20]
This is a search engine problem and makes indeed difficult. Redirect base to www via 30x redirect.

**Comment by deejoe** [comment]
Sorry, not sure what you mean.  I give my browser 'interlockroc.org' and it redirects.

Can you give a more specific example?

**Comment by antitree** [comment]
Resolved. This was an issue related to SEO. having both WWW and "." means that there would be inconsistency in links and appear as two different websites to search engines. Resolved via Github hosting.
