### ISSUE TITLE
Interlock logo very small behind macro image

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io.src#21]
The header is huge compared to the logo. Replace logo with appropriate sized header or resize logo to not have such padding

**Comment by deejoe** [comment]
Yeah, rescaling the images is a thing that'd be pretty straightforward for me to do. 

The red 3D-printed space invader against blue painters tape source file is 

./themes/clean-blog/static/images/home-bg.jpg

and gets rendered to

./output/theme/images/home-bg.jpg

'identify' shows it as

JPEG 2048x1365 2048x1365+0+0 8-bit sRGB 1.053MB 0.000u 0:00.009

Not sure what I'd resize it down to, or if the theme would just expand it anyway.  Worth a look, but if any web wizards want to weigh in, feel free.

**Comment by deejoe** [comment]
See also https://github.com/Interlock-Rochester/interlock-rochester.github.io/issues/3

**Comment by antitree** [comment]
migrated to https://github.com/Interlock-Rochester/interlock-rochester.github.io/issues/11
