### ISSUE TITLE
Hyperlinks do not show they are links

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io.src#24]
The contact page doesn't show which links are links unless you hover. Not sure if all pages

**Comment by deejoe** [comment]
Yeah, this is another style/design thing that doesn't play to my strengths. 

Patches welcome

**Comment by deejoe** [comment]
On Sat, Aug 19, 2017 at 02:04:14PM +0000, D. Joe wrote:
> Yeah, this is another style/design thing that doesn't play to my strengths.
> 
> Patches welcome

Thanks to @adamhayes for keeping this one alive via some attention last
night and today. Via IRC earlier today:

15:26 <+dzho> https://www.w3schools.com/css/css_link.asp
15:31 <+dzho> themes/clean-blog/static/css/clean-blog.css
15:31  * dzho guesses that must be what to add, and that must be the place

**Comment by antitree** [comment]
Migrated to https://github.com/Interlock-Rochester/interlock-rochester.github.io/issues/10
