### ISSUE TITLE
Meetup.com not referenced on website

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io.src#25]
Maybe I can't find out but first glance there's no reference to Meetup which is our main meeting page

**Comment by atpage** [comment]
It's on the wiki but it's a broken link.

**Comment by deejoe** [comment]
By "on the wiki" do you mean the link for Meetup found here?

http://wiki.interlockroc.org/wiki/index.php/Promotion

That whole page is hilariously outdated. The need for it remains, though, so in lieu of a total overhaul we should probably keep it and work on updating it best we can.

http://www.meetup.com/Rochester-Hackerspace

(If I correctly recall what happened, antitree ran that meetup, then we tried going without it for a while, possibly dropping that instance, then decided to use meetup again, and that brings us to the current instance.)

**Comment by atpage** [comment]
Yep.  Most of the wiki is outdated, broken, or redundant.  I have a wiki account now, and plan to start getting rid of stuff that is already on interlockroc.org.  Then we can discuss how to handle the rest of it.
