### ISSUE TITLE
Sync content between Meetup and website

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io.src#26]

**Comment by deejoe** [comment]
For anyone wanting to work on this, I think this is the "Meetup" referred to above:

https://www.meetup.com/Interlock-Rochester-Hackerspace/

**Comment by NTICompass** [comment]
Or we can use something like https://github.com/munen/meetup-calendar (we can iframe this, but it's not styled much) or we can run our own hosted app that can do this and throws us the HTML.

http://meetup-calendar.herokuapp.com/meetup/Interlock-Rochester-Hackerspace

**Comment by antitree** [comment]
We'll call this issue resolved in that we have a link to the meetup calendar on the main home page and we reference meetup in the contact page. The bigger picture fix will have to be a new issue.
