### ISSUE TITLE
Mobile: logo text not visible

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io.src#28]
You can't see Rochester from the logo. It's lost in the header

**Comment by deejoe** [comment]
Well, not that I'm defending the design or anything, but I can see it, so clearly this is in some way dependent on the browser environment.

In order that we might be able to reproduce and test this, can you say more about the environment in which you see this? Care to provide a screenshot?

**Comment by antitree** [comment]
Moved to https://github.com/Interlock-Rochester/interlock-rochester.github.io/issues/7
