### ISSUE TITLE
Various instances of version skew revealed in a theme bug

### ISSUE THREAD

**Issue by deejoe** [Interlock-Rochester/interlock-rochester.github.io.src#3]
So, we have a couple of types of version skew going on.

First, @aks4896 is using apt-get to install his distro's version of Pelican. This is a righteous move and not a problem on it's own. It has much to recommend it. I, however, have done something akin to the following:

    mkdir interlock-web
    cd interlock-web
    virtualenv venv
    source venv/bin/activate
    pip install pelican markdown
    git clone https://github.com/Interlock-Rochester/interlock-rochester.github.io.src
    cd interlock-rochester.github.io.src
    # faffing around with the site configuration, or with stuff in content/
    make clean; make html ; make serve 
    # point local browser to localhost:8000 to test
    # some sort of deployment from output/

This, also, is a righteous move and has much to recommend it. 

The problem though is that the theme @aks4896 has chosen (again, a good choice, nothing wrong so far), has a bug that manifests *only* in newer versions of Pelican, eg, what I have been using, and not what @aks4896 has been using.

As played out in [IRC at freenode's #interlock-rochester](http://webchat.freenode.net/?channels=%23interlock&uio=d4) (lightly-edited for local refs):

<pre>
12:18 < [@deejoe]> so, looks like I'm getting bit by this bug 
              https://github.com/gilsondev/pelican-clean-blog/pull/53

12:21 < [@deejoe]> I was blaming [@aks4896] for not putting in the right place changes he 
              made to enable display of links in the pelican blog header to 
              pages (about, calendar, etc), but it's just this mismatch, the 
              clean-blog theme not having caught up to a change in Pelican.
[... @aks4896 asks if they're using an old version ...]
14:25 < [@deejoe]> [@aks4896]: I don't know which version you're using, I can only infer 
              it's old from a) that you do apt-get to get it and b) that I'm 
              using pip install to get mine.
14:26 < [@deejoe]> the distro creation and release process guarantees version lag. 
              Sometimes this is good, sometimes its bad, sometimes it just is.
</pre>

My proposed remedy would be to 

  * bite the keeping-up-with-versions bullet, settle on virtualenv/pip as the recommended development environment due to it being more cross-platform and to offer finer grained control of versions not just of Pelican, but of its dependencies as well.
   * deal with the clean-blog theme bug by making our own clone of it (sorry, in github-context, a _fork_), apply the indicated patch, and install our theme from our own clone.

I'll begin working on this in its own branch, but wanted to get this out there for consideration. If trying things this way is a non-starter for whatever reason for anyone else, not much point in my going further with it anyway.

Discuss, please.

**Comment by deejoe** [comment]
In the meantime, @aks4896 if you could figure out which version of Pelican you're using, I could also see about installing that version in a virtualenv so that I can be bug compatible with the version of [pelican-clean-blog](https://github.com/gilsondev/pelican-clean-blog/pull/53) currently in place.

(also this comment gives us a live link to the bug, which I realize the previous comment does not offer now that I have the IRC quote pre-formatted.)

**Comment by aks4896** [comment]
$ pelican --version
3.6.3

**Comment by antitree** [comment]
Moved to https://github.com/Interlock-Rochester/interlock-rochester.github.io/issues/12
