### ISSUE TITLE
Where to host?

### ISSUE THREAD

**Issue by deejoe** [Interlock-Rochester/interlock-rochester.github.io.src#34]
This so far has been buried in this and related issues:

https://github.com/Interlock-Rochester/interlock-rochester.github.io.src/issues/19

but I want to surface this as its own item:

Do we want to continue hosting on ghpt's Linode VPS or use GitHub pages? If the latter, who wants to step up and make that happen?

We can bruit around pros and cons here, and any next steps for either platform.

**Comment by deejoe** [comment]
One con with the current system is that deployment is clunky and with me as a bottleneck and single-point of failure. Staying with this the VPS hosting would probably mean adding some automation to the process.

**Comment by antitree** [comment]
Migrating to github hosting
