### ISSUE TITLE
Article summary should strip HTML before truncating to 140 characters

### ISSUE THREAD

**Issue by jnwatts** [Interlock-Rochester/interlock-rochester.github.io.src#4]
https://github.com/Interlock-Rochester/interlock-rochester.github.io.src/blob/master/themes/clean-blog/templates/index.html#L33

I presume there's a filter that can strip HTML. Another option would be to skip truncation and manually fill in a plain-text summary for each article (at least those on front-page).

**Comment by aks4896** [comment]
This is in relation to this:
![image](https://cloud.githubusercontent.com/assets/1131608/23867198/88a0f310-07f1-11e7-856e-19030becc712.png)

Thanks for helping out Josh!!
