### ISSUE TITLE
.md pages are not being processed into .html

### ISSUE THREAD

**Issue by ghost** [Interlock-Rochester/interlock-rochester.github.io.src#44]
Starting Sept 6th (after moving to new hosting?), the .md pages in content/pages/ do not render into html.  Consequently, they don't show up as nav items at the top of the page, and you can't access them directly using, e.g. http://www.interlockroc.org/pages/members.html

We could just go to .rst files for everything..

@deejoe @antitree

**Comment by deejoe** [comment]
On Wed, Sep 06, 2017 at 01:17:27PM +0000, Adam Hayes wrote:
> Starting Sept 6th (after moving to new hosting?), the .md pages in content/
> pages/ do not render into html. Consequently, they don't show up as nav items
> at the top of the page, and you can't access them directly using, e.g. http://
> www.interlockroc.org/pages/members.html
> 
> We could just go to .rst files for everything..
> 
> @deejoe @antitree

Alas, it seems that loading markdown *is* specified in the config file for
Travis:

https://github.com/Interlock-Rochester/interlock-rochester.github.io/blob/src/.travis.yml

One might try switching the order of the markdown and pelican entries in the
pip install line to make sure it isn't just reading the first thing, I
guess, but that's a long shot.

-- 
Joe

**Comment by antitree** [comment]
Issue has been addressed. Please add issues to new repo: https://github.com/Interlock-Rochester/interlock-rochester.github.io.src/issues/
